framework:
    cache:
        # file system cache adapter (/var/cache)
        app: cache.adapter.filesystem
        system: cache.adapter.system

        # other cache adapters
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
